[package]
name = "shards-tech/size"
description = "Returns the size of dependencies or scripts on a Folder or Instance (Plugin Only). https://github.com/shards-tech/size.git"
authors = ["Bloomy <dequeyuri@gmail.com>"]

version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["init.lua", "wally.toml"]
